src/tweetme/accounts/api/urls.py
from django.urls import path
from tweets.api.views import (TweetListApiView)

app_name = 'tweet'
urlpatterns = [
    path('<slug:username>/tweet/', TweetListApiView.as_view(), name='list'),
]

src/tweetme/accounts/urls.py
from django.urls import path
from .views import (UserDetailView, UserFollowView)
from django.views.generic.base import RedirectView

app_name = 'profiles'
urlpatterns = [
    # path('', RedirectView.as_view(url="/"), name='home'),
    # path('search/', TweetListView.as_view(), name='list'),
    path('<slug:username>', UserDetailView.as_view(), name='detail'),
    path('<slug:username>/follow/', UserFollowView.as_view(), name='follow'),
    # path('create/', TweetCreateView.as_view(), name='create'),
    # path('<int:pk>/update', TweetUpdateView.as_view(), name='update'),
    # path('<int:pk>/delete', TweetDeleteView.as_view(), name='delete'),

]

src/tweetme/tweets/urls.py
from django.urls import path
from .views import (TweetDetailView, TweetListView,
                    TweetCreateView, TweetUpdateView, TweetDeleteView, RetweetView)
from django.views.generic.base import RedirectView

app_name = 'tweet'
urlpatterns = [
    path('', RedirectView.as_view(url="/"), name='home'),
    path('search/', TweetListView.as_view(), name='list'),
    path('<int:pk>', TweetDetailView.as_view(), name='detail'),
    path('<int:pk>/retweet/', RetweetView.as_view(), name='detail'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/update', TweetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', TweetDeleteView.as_view(), name='delete'),

]

src/tweetme/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.db.models.signals import post_save
# Create your models here.


class UserProfileManager(models.Manager):
    use_for_related_fields = True

    def all(self):
        qs = self.get_queryset().all()
        print(self)
        print(dir(self))
        print(self.instance)
        try:
            if self.instance:
                qs = qs.exclude(user=self.instance)
        except:
            pass
        return qs

    def toggle_follow(self, user, to_toggle_user):
        user_profile, created = UserProfile.objects.get_or_create(
            user=user)
        if to_toggle_user in user_profile.following.all():
            user_profile.following.remove(to_toggle_user)
            added = False
        else:
            user_profile.following.add(to_toggle_user)
            added = True
        return added

    def is_following(self, user, followed_by_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if created:
            return False
        if followed_by_user in user_profile.following.all():
            return True
        return False


class UserProfile (models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
    following = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='followed_by')
    # ! user.profile.following -- users followed
    # ! user.followed_by -- followed by users

    objects = UserProfileManager()  # ! UserProfile.objects.all()

    def __str__(self):
        return str(self.following.all().count())

    def get_following(self):
        user = self.following.all()
        return user.exclude(username=self.user.username)

    def get_follow_url(self):
        return reverse_lazy('profiles:follow', kwargs={"username": self.user.username})

    def get_absolute_url(self):
        return reverse_lazy('profiles:detail', kwargs={"username": self.user.username})


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        new_profile = UserProfile.objects.get_or_create(user=instance)


post_save.connect(post_save_user_receiver, sender=settings.AUTH_USER_MODEL)

src/tweetme/tweets/models.py
import re
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from .validators import validate_content
from django.urls import reverse
from hashtags.signals import parsed_hashtags
from django.utils import timezone
from django.db.models.signals import post_save
# Create your models here.


class TweetManager(models.Manager):
    def retweet(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj

        qs = self.get_queryset().filter(
            user=user, parent=og_parent
        ).filter(
            timestamp__year=timezone.now().year,
            timestamp__month=timezone.now().month,
            timestamp__day=timezone.now().day,
        )
        if qs.exists():
            return None
        obj = self.model(
            parent=og_parent,
            user=user,
            content=parent_obj.content,
        )
        obj.save()

        return obj

    def like_toggle(self, user, tweet_obj):
        if user in tweet_obj.liked.all():
            is_liked = False
            tweet_obj.liked.remove(user)
        else:
            is_liked = True
            tweet_obj.liked.add(user)
        return is_liked


class Tweet(models.Model):
    parent = models.ForeignKey(
        "self", blank=True, null=True, on_delete=models.CASCADE)
    # user
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    content = models.CharField(max_length=140, validators=[validate_content, ])
    liked = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = TweetManager()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('tweet:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ["-timestamp"]

    # def clean(self, *args, **kwargs):
    #     content = self.content
    #     if content == 'abc':
    #         raise ValidationError('Content cannot be ABC')
    #     return super(Tweet, self).clean(*args, **kwargs)


def tweet_save_receiver(sender, instance, created, *args, **kwargs):
    if created and not instance.parent:
        # ? @ getting usernames
        user_regex = r'@(?P<username>[\w.@+-]+)'
        usernames = re.findall(user_regex, instance.content)
        # ? getting hashtags
        hash_regex = r'#(?P<hashtag>[\w\d-]+)'
        hashtags = re.findall(hash_regex, instance.content)
        parsed_hashtags.send(hashtag_list=hashtags, sender=instance.__class__)
        # ? sending hashtag signal to user


post_save.connect(tweet_save_receiver, sender=Tweet)

src/tweetme/accounts/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from .models import UserProfile
User = get_user_model()
# Create your views here.


class UserDetailView(DetailView):
    template_name = 'accounts/user_detail.html'
    queryset = User.objects.all()

    def get_object(self):
        return get_object_or_404(User, username__iexact=self.kwargs.get('username'))

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(*args, **kwargs)
        following = UserProfile.objects.is_following(
            self.request.user, self.get_object())
        context['following'] = following
        return context


class UserFollowView(View):
    def get(self, request, username, *args, **kwargs):
        toggle_user = get_object_or_404(User, username__iexact=username)
        if request.user.is_authenticated:
            is_following = UserProfile.objects.toggle_follow(
                request.user, toggle_user)
        return redirect('profiles:detail', username=username)

src/tweetme/accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% block script %}
<script>
    $(document).ready(function () {
        loadTweetContainer("tweet-container");
    });
</script>
{% endblock script %}
{% block body %}
<div class="card shadow-lg">
    <div class="card-body">
        <div class="row p-2">
            <div class="col-3 bg-dark">
                <h1 class="text-white mt-3">{{ object.username }}</h1>
                <h3 class="text-white mt-3">Followers: {{object.followed_by.all.count }}</h3>
                <p><a class="btn btn-link" href="{{ object.profile.get_follow_url }}">
                        {% if following %} Unfollow {% else %} Follow {% endif %}
                    </a></p>
            </div>
            <div class="col-9">
                <div class="media mt-4">
                    <div class="media-body">
                        <h1>Tweets <small>({{object.tweet_set.all.count}})</small></h1>
                        <div id="tweet-container" data-url="/api/{{user.username}}/tweet/">

                        </div>
                        <a href="#" id="LoadMore">Load more tweets</a>

                        <hr />
                        <h1>Following <small>({{object.profile.get_following.count}})</small></h1>
                        {% for user in object.profile.get_following %}
                        <h6><a href="/{{ user.username }}">{{user.username}}</a></h6>
                        {% empty %}
                        <h6>Not following any users</h6>
                        {% endfor %}
                        <hr />
                        <h1>Followed By <small>({{object.followed_by.all.count}})</small></h1>
                        {% for profile in object.followed_by.all %}
                        <h6><a href="/{{ profile.user.username }}">{{profile.user.username}}</a></h6>
                        {% empty %}
                        <h6>Not followed by any users</h6>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}